routes/web.php
<?php
/*Services*/
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*Controller*/
use App\Http\Controllers\PagesController;
use App\Http\Controllers\HomeController;
/*Master*/
use App\Http\Controllers\m3\UsersController;
use App\Http\Controllers\m3\CategorysController;
use App\Http\Controllers\m3\CommentController;
use App\Http\Controllers\m3\PagesController as M3PagesController;
use App\Http\Controllers\m3\PostsController;
/*User*/
use App\Http\Controllers\user\UserController;
use App\Http\Controllers\user\PostController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class, 'index'])->name('index');

Auth::routes(['verify' => true]);

Route::get('/home',[HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth','verified']], function () {
	
	//User
	Route::resource('conta', UserController::class);
	Route::resource('postagens', PostController::class);

	//Master
	Route::resource('categories', CategorysController::class);
	Route::resource('users', UsersController::class)->except([
		'create'
	]);
	Route::resource('posts', PostsController::class)->except([
		'create','store'
	]);
	Route::resource('comentarios', CommentController::class)->except([
		'index','create','edit',
	]);
	Route::resource('pages', M3PagesController::class)->except([
		'create','show','store','destroy'
	]);

	//Site
	Route::get('categoria/{slug}', [PagesController::class, 'posts'])->name('posts');
	Route::get('post/{slug}', [PagesController::class, 'post'])->name('post');
	Route::get('user/{slug}', [PagesController::class, 'user'])->name('user');
	Route::post('comments', [PagesController::class, 'comments'])->name('comments');
	Route::get('curti/{id}', [PagesController::class, 'curti'])->name('curti');
	
	
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\m3\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\m3\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade'); 
	Route::get('map', function () {return view('pages.maps');})->name('map');
	Route::get('icons', function () {return view('pages.icons');})->name('icons'); 
	Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\m3\ProfileController@password']);

	//Pages Statics
	Route::get('{slug}', [PagesController::class, 'pages'])->name('pages');	
});

app/Http/Controllers/api/UsersController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\User;

class UsersController extends Controller
{

    public function validated($request)
    {
        return Validator::make($request->all(), [
            'name' => ['required', 'min:3'],
            'email' => ['required', 'email:rfc,dns'],
            'cpf' => ['required'],
            'password' => ['required', 'confirmed', 'min:6']
        ]);

    }

    public function store(Request $request)
    {
        if (self::validated($request)->fails()) 
            return response()->json(['error' => self::validated($request)->errors()->first()]);

        $user = new User;
        $user->setData($user, $request->all());

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return response()->json(['error' => 'Erro ao realizar cadastro. Por favor tente novamente.']);
        }

        return response()->json(['success' => 'Usuário Cadastrado com Sucesso!']);
    }

    
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        //
    }

   
    public function update(Request $request, $id)
    {
        //
    }

  
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/m3/UsersController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, 'user');
    }
    
    public function index()
    {
        return view('m3.users.index');
    }

    
    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        $type = Role::where('name','User')->first();
        $user = new User;

        $user->setData($user, $request->all());   
        $user->role_id = $type->id;

        try {
            $user->save();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível cadastrar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário cadastrado com sucesso!');
    }

    
    public function show(User $user)
    {
        return view('m3.users.show',['user' => $user]);
    }

    
    public function edit(User $user)
    {
        return auth()->user()->role->name === "User" ? 
            redirect()->route('conta.edit', $user) : 
                view('m3.users.edit',['user' => $user]);
    }

    
    public function update(Request $request, User $user)
    {
        $user->setData($user, $request->all());

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Não foi possível atualizar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário atualizado com sucesso!');
    }

    
    public function destroy(User $user)
    {
        if(isset($user->post)):
            foreach($user->post as $item):
                $item->delete();
            endforeach;
        endif;

        try {
            $user->delete();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível apagar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário apagado com sucesso!');
    }
}

app/Http/Controllers/user/AdminController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view('user.index');
    }
}

app/Http/Controllers/user/PostController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\File;
use App\Models\FilesHasPosts;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;
use App\Models\FeaturedPost;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    public $post;

    public function __construct(Post $post)
    {
        $this->post = $post;
    }
    
    public function index()
    {
        //
    }

    
    public function create()
    {
        $this->authorize('create', Post::class);
        return view('user.posts.create',['categorys' => Category::orderBy('title','asc')->get()]);
    }

    
    public function store(PostRequest $request)
    {
        $this->authorize('create', Post::class);
        
        $post = new Post;
        $file = new File;
        $has = new FilesHasPosts;

        $post->setData($post, $request->all());
        $post->user_id = auth()->user()->id;

        try {
            $post->save();

            FeaturedPost::create(['post_id' => $post->id]);

            try {
                $file->upload($file, $request->file, auth()->user()->id);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao cadastrar imagem. Por favor tente novamente.');
            }

            $has->file_id = $file->id;
            $has->post_id = $post->id;

            try {
                
                $has->save();

            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao cadastrar imagem. Por favor tente novamente.');
            }
        } catch (\Throwable $th) {
            throw $th;
            return redirect()->back()->with('error', 'Erro ao cadastrar Post. Por favor tente novamente.');
        }

        return redirect()->route('home')->with('success', 'Post cadastrado e em análise.');
    }

    
    public function show(Post $post)
    {
        //
    }

    
    public function edit($id)
    {
        $this->authorize('update', $this->post->find($id));
        // dd($this->post->find($id));
        return view('user.posts.edit',['post' => $this->post->find($id), 'categorys' => Category::orderBy('title','asc')->get()]);
    }

    
    public function update(PostRequest $request, $id)
    {
        $post = $this->post->find($id);
        $this->authorize('update', $post);

        $post->setData($post, $request->all());
        $post->user_id = auth()->user()->id;

        try {
            $post->save();

        } catch (\Throwable $th) {
            throw $th;
            return redirect()->back()->with('error', 'Erro ao atualizar Post. Por favor tente novamente.');
        }

        if($request->file):
            $file = new File;
            $has = new FilesHasPosts;

            try {
                $file->upload($file, $request->file, auth()->user()->id);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao atualizar imagem. Por favor tente novamente.');
            }

            $has->file_id = $file->id;
            $has->post_id = $post->id;

            try {
                
                $has->save();

            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao atualizar imagem. Por favor tente novamente.');
            }
        endif;

        return redirect()->route('home')->with('success', 'Post atualizado e em análise.');
    }

    
    public function destroy($id)
    {
        $post = $this->post->find($id);
        $this->authorize('delete', $post);

        // dd($post->comment);
        try {
            $post->hasFile ? Storage::disk('public')->delete($post->hasFile->file->path) : '';
            if($post->comment->count() >= 1){

                foreach($post->comment as $item):
                    $item->delete();
                endforeach;
            }

            $post->delete();
            
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Erro ao exluir imagem. Por favor tente novamente.');
        }

        return redirect()->route('home')->with('success', 'Post apagado com sucesso.');
    }
}

app/Http/Controllers/user/UserController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use App\Models\File;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function index()
    {
        return view('user.index');
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        
    }

   
    public function show($id)
    {

    }

    
    public function edit($id)
    {
        $this->authorize('update', $this->user->find($id));
        return view('user.account.edit',['user' => $this->user->find($id)]);
    }

    
    public function update(Request $request, $id)
    {
        $user = $this->user->find($id);
        $this->authorize('update', $user);

        if($request->file):

            $validator = Validator::make($request->all(), [
                'file' => 'max:300',    
            ]);

            if ($validator->fails()) {
                return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
            }

            $file = new File;

            try {
                $file->upload($file, $request->file, auth()->user()->id);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao cadastrar imagem. Por favor tente novamente.');
            }
            $user->file_id = $file->id;
        endif;

        $user->setData($user, $request->all());
        

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Erro ao atualizar cadastro. Por favor tente novamente.');
        }



        return redirect()->route('home')->with('success', 'Dados atualizado com Sucesso!');
    }

    
    public function destroy(User $user)
    {
        //
    }
}

app/Http/Livewire/Site/Posts/User.php
<?php

namespace App\Http\Livewire\Site\Posts;

use Livewire\Component;

class User extends Component
{
    public $user;
    public $date;
    public $post;

    public function render()
    {
        // dd($this->post->like->count());
        // dd($this->date->format('d-m-y'));
        return view('livewire.site.posts.user',['user' => $this->user,'date' => $this->date, 'post' => $this->post]);
    }
}

app/Http/Livewire/Users/Cards.php
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class Cards extends Component
{
    public $data;

    public function cards($item)
    {
        return [
            [
                'title' => 'Produtos',
                'icon' => 'shop text-default',
                'count' => $item->products->count(),
                'route' => 'companies.products.show',
                'id' => $item->id,
            ],
            [
                'title' => 'Slides',
                'icon' => 'tv-2 text-warning',
                'count' => $item->slides->count()
            ],
            [
                'title' => 'Configurações',
                'icon' => 'settings-gear-65 text-danger',
                'count' => $item->settings->count()
            ],
            [
                'title' => 'Logs',
                'icon' => "cloud-download-95 text-primary",
                'count' => $item->users->logs->count()
            ]
        ];
    }

    public function render()
    {
        return view('livewire.cards',['cards' => $this->cards($this->data)]);
    }
}

app/Http/Livewire/Users/Lists.php
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;
use App\Models\User;
use Livewire\WithPagination;

class Lists extends Component
{
    use WithPagination;

     public $search;

    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        return view('livewire.users.lists',[
            'users' => User::where([
                ['email','!=',auth()->user()->email],
                ['name', 'like', '%'.$this->search.'%']
            ])->paginate(15)
        ]);
    }
}

app/Http/Livewire/Users/Posts.php
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class Posts extends Component
{
    public $posts;

    public function render()
    {
        return view('livewire.users.posts',['posts' => $this->posts]);
    }
}

resources/views/user/account/edit.blade.php
<x-site>
    <x-slot name="title">
        {{ __('Preferências') }}
    </x-slot>

    <x-slot name="css">
        <style type="text/css">
            .btn-danger .file-upload {
                width: 100%;
                padding: 10px 0px;
                position: absolute;
                left: 0;
                opacity: 0;
                cursor: pointer;
            }

        </style>
    </x-slot>

    <x-slot name="content">
        <section class="container">
            <div class="pt-5 pb-4">
                <h3>
                    <strong>Preferências</strong>
                </h3>
            </div>
            <form class="admin-form" method="POST" enctype="multipart/form-data"
                action="{{ route('conta.update', auth()->user()->id) }}">
                @csrf
                @method('put')
                <div class="form-row">
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="">Nome <em class="text-danger">*</em></label>
                        <input type="text" name="name"
                            class="form-control rounded-0 @error('name') is-invalid @enderror"
                            value="{{ $user->name }}">
                        @error('name')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="">E-mail <em class="text-danger">*</em></label>
                        <input type="email" name="email"
                            class="form-control rounded-0 @error('email') is-invalid @enderror"
                            value="{{ $user->email }}">
                        @error('email')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-4">
                        <label for="">Usuário <em class="text-danger">*</em></label>
                        <input type="text" name="text"
                            class="form-control rounded-0 @error('name') is-invalid @enderror"
                            value="{{ $user->name }}" disabled>
                        @error('name')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-4">
                        <label for="">Senha</label>
                        <input type="password" name="password"
                            class="form-control rounded-0 @error('password') is-invalid @enderror">
                        @error('password')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-4">
                        <label for="">Confirmar Senha</label>
                        <input type="password" name="password_confirmation"
                            class="form-control rounded-0 @error('password_confirmation') is-invalid @enderror">
                        @error('password_confirmation')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-sm-12 col-md-4 admin" style="background-color: transparent">
                        <div class="d-flex justify-content-center align-items-center flex-column">
                            <img src="{{ asset(auth()->user()->file ? Storage::url(auth()->user()->file->path) : '/images/min/avatar-woman.svg') }}"
                                class="avatar" id="imagem">
                            <div class="btn btn-sm btn-danger">
                                <input type="file" class="file-upload" id="file-upload" name="file" accept="image/*">
                                Atualizar imagem
                            </div>
                        </div>
                        @error('file')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-8">
                        <label>Sobre</label>
                        <textarea name="about"
                            class="form-control h-auto rounded-0 @error('about') is-invalid @enderror"
                            rows="7">{{ $user->about ?? old('about') }}</textarea>
                        @error('about')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <label for="">Facebook</label>
                        <input type="text" name="facebook"
                            class="form-control rounded-0 @error('facebook') is-invalid @enderror"
                            value="{{ $user->facebook }}">
                        @error('facebook')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <label for="">Instagram</label>
                        <input type="text" name="facebook"
                            class="form-control rounded-0 @error('instagram') is-invalid @enderror"
                            value="{{ $user->instagram }}">
                        @error('instagram')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                </div>
                <div class="text-right login">
                    <button type="submit" class="btn btn-success">atualizar</button>
                </div>
            </form>
        </section>
    </x-slot>
    <x-slot name="js">
        <script type="text/javascript">
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader()
                    reader.onload = function(e) {
                        $('#imagem').attr('src', e.target.result)
                    }
                    reader.readAsDataURL(input.files[0])
                }
            }
            $('#file-upload').change(function() {
                readURL(this)
            })

        </script>
    </x-slot>
</x-site>