routes/web.php
<?php
/*Services*/
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*Controller*/
use App\Http\Controllers\PagesController;
use App\Http\Controllers\HomeController;
/*Master*/
use App\Http\Controllers\m3\UsersController;
use App\Http\Controllers\m3\CategorysController;
use App\Http\Controllers\m3\CommentController;
use App\Http\Controllers\m3\PagesController as M3PagesController;
use App\Http\Controllers\m3\PostsController;
/*User*/
use App\Http\Controllers\user\UserController;
use App\Http\Controllers\user\PostController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class, 'index'])->name('index');

Auth::routes(['verify' => true]);

Route::get('/home',[HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth','verified']], function () {
	
	//User
	Route::resource('conta', UserController::class);
	Route::resource('postagens', PostController::class);

	//Master
	Route::resource('categories', CategorysController::class);
	Route::resource('users', UsersController::class)->except([
		'create'
	]);
	Route::resource('posts', PostsController::class)->except([
		'create','store'
	]);
	Route::resource('comentarios', CommentController::class)->except([
		'index','create','edit',
	]);
	Route::resource('pages', M3PagesController::class)->except([
		'create','show','store','destroy'
	]);

	//Site
	Route::get('categoria/{slug}', [PagesController::class, 'posts'])->name('posts');
	Route::get('post/{slug}', [PagesController::class, 'post'])->name('post');
	Route::get('user/{slug}', [PagesController::class, 'user'])->name('user');
	Route::post('comments', [PagesController::class, 'comments'])->name('comments');
	Route::get('curti/{id}', [PagesController::class, 'curti'])->name('curti');
	
	
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\m3\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\m3\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade'); 
	Route::get('map', function () {return view('pages.maps');})->name('map');
	Route::get('icons', function () {return view('pages.icons');})->name('icons'); 
	Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\m3\ProfileController@password']);

	//Pages Statics
	Route::get('{slug}', [PagesController::class, 'pages'])->name('pages');	
});

app/Http/Controllers/api/PostsController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Post;
use App\Models\File;
use App\Models\FilesHasPosts;


class PostsController extends Controller
{
    
    public function validated($request)
    {
        return Validator::make($request->all(), [
            'title' => ['required', 'min:3'],
            'category_id' => ['required', 'uuid'],
            'file' => ['required','image', 'max:300'],
            'content' => ['required'],
        ]);

    }


    public function categorys()
    {
        return response()->json(Category::allCategory());
    }


    public function store(Request $request)
    {
        if (self::validated($request)->fails()) 
            return response()->json(['error' => self::validated($request)->errors()->first()]);
        
        $post = new Post;
        $file = new File;
        $has = new FilesHasPosts;

        $post->setData($post, $request->all());

        try {
            $post->save();

            try {
                $file->upload($file, $request->file, 'teste');
            } catch (\Throwable $th) {
                throw $th;
                return response()->json(['error' => 'Erro ao cadastrar imagem. Por favor tente novamente.']);
            }

            $has->file_id = $file->id;
            $has->post_id = $post->id;

            try {
                
                $has->save();

            } catch (\Throwable $th) {
                throw $th;
                return response()->json(['error' => 'Erro ao cadastrar imagem. Por favor tente novamente.']);
            }
        } catch (\Throwable $th) {
            throw $th;
            return response()->json(['error' => 'Erro ao cadastrar Post. Por favor tente novamente.']);
        }

        return response()->json(['success' => 'Post cadastrado e em análise.']);

    }

}

app/Http/Controllers/api/UsersController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\User;

class UsersController extends Controller
{

    public function validated($request)
    {
        return Validator::make($request->all(), [
            'name' => ['required', 'min:3'],
            'email' => ['required', 'email:rfc,dns'],
            'cpf' => ['required'],
            'password' => ['required', 'confirmed', 'min:6']
        ]);

    }

    public function store(Request $request)
    {
        if (self::validated($request)->fails()) 
            return response()->json(['error' => self::validated($request)->errors()->first()]);

        $user = new User;
        $user->setData($user, $request->all());

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return response()->json(['error' => 'Erro ao realizar cadastro. Por favor tente novamente.']);
        }

        return response()->json(['success' => 'Usuário Cadastrado com Sucesso!']);
    }

    
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        //
    }

   
    public function update(Request $request, $id)
    {
        //
    }

  
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/m3/PostsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\FeaturedPost;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class, 'post');
    }

    public function index()
    {
        return view('m3.posts.index');
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        //
    }

    
    public function show(Post $post)
    {
        return view('m3.comments.index',['post' => $post]);
    }

    
    public function edit(Post $post)
    {
        return view('m3.posts.edit', ['post' => $post, 'categorys' => Category::orderBy('title', 'asc')->get()]);
    }

    
    public function update(Request $request, Post $post)
    {
        try {
            $post->update($request->all());
            FeaturedPost::where('post_id',$post->id)->update(['active' => $request->featured_post, 'post_id' => $post->id]);
        } catch (\Throwable $th) {
            throw $th;
            return redirect()->back()->with('error', 'Erro ao atualizar post!');
        }

        return redirect()->route('posts.index')->with('success','Post atualizado com sucesso!');
    }

    
    public function destroy(Post $post)
    {
        try {
            $post->delete();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível apagar o post.');
        }

        return redirect()->back()->with('success', 'Post removido com sucesso!');
    }
}

app/Http/Controllers/m3/UsersController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, 'user');
    }
    
    public function index()
    {
        return view('m3.users.index');
    }

    
    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        $type = Role::where('name','User')->first();
        $user = new User;

        $user->setData($user, $request->all());   
        $user->role_id = $type->id;

        try {
            $user->save();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível cadastrar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário cadastrado com sucesso!');
    }

    
    public function show(User $user)
    {
        return view('m3.users.show',['user' => $user]);
    }

    
    public function edit(User $user)
    {
        return auth()->user()->role->name === "User" ? 
            redirect()->route('conta.edit', $user) : 
                view('m3.users.edit',['user' => $user]);
    }

    
    public function update(Request $request, User $user)
    {
        $user->setData($user, $request->all());

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Não foi possível atualizar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário atualizado com sucesso!');
    }

    
    public function destroy(User $user)
    {
        if(isset($user->post)):
            foreach($user->post as $item):
                $item->delete();
            endforeach;
        endif;

        try {
            $user->delete();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível apagar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário apagado com sucesso!');
    }
}

app/Http/Controllers/user/AdminController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view('user.index');
    }
}

app/Http/Controllers/user/PostController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\File;
use App\Models\FilesHasPosts;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;
use App\Models\FeaturedPost;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    public $post;

    public function __construct(Post $post)
    {
        $this->post = $post;
    }
    
    public function index()
    {
        //
    }

    
    public function create()
    {
        $this->authorize('create', Post::class);
        return view('user.posts.create',['categorys' => Category::orderBy('title','asc')->get()]);
    }

    
    public function store(PostRequest $request)
    {
        $this->authorize('create', Post::class);
        
        $post = new Post;
        $file = new File;
        $has = new FilesHasPosts;

        $post->setData($post, $request->all());
        $post->user_id = auth()->user()->id;

        try {
            $post->save();

            FeaturedPost::create(['post_id' => $post->id]);

            try {
                $file->upload($file, $request->file, auth()->user()->id);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao cadastrar imagem. Por favor tente novamente.');
            }

            $has->file_id = $file->id;
            $has->post_id = $post->id;

            try {
                
                $has->save();

            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao cadastrar imagem. Por favor tente novamente.');
            }
        } catch (\Throwable $th) {
            throw $th;
            return redirect()->back()->with('error', 'Erro ao cadastrar Post. Por favor tente novamente.');
        }

        return redirect()->route('home')->with('success', 'Post cadastrado e em análise.');
    }

    
    public function show(Post $post)
    {
        //
    }

    
    public function edit($id)
    {
        $this->authorize('update', $this->post->find($id));
        // dd($this->post->find($id));
        return view('user.posts.edit',['post' => $this->post->find($id), 'categorys' => Category::orderBy('title','asc')->get()]);
    }

    
    public function update(PostRequest $request, $id)
    {
        $post = $this->post->find($id);
        $this->authorize('update', $post);

        $post->setData($post, $request->all());
        $post->user_id = auth()->user()->id;

        try {
            $post->save();

        } catch (\Throwable $th) {
            throw $th;
            return redirect()->back()->with('error', 'Erro ao atualizar Post. Por favor tente novamente.');
        }

        if($request->file):
            $file = new File;
            $has = new FilesHasPosts;

            try {
                $file->upload($file, $request->file, auth()->user()->id);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao atualizar imagem. Por favor tente novamente.');
            }

            $has->file_id = $file->id;
            $has->post_id = $post->id;

            try {
                
                $has->save();

            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao atualizar imagem. Por favor tente novamente.');
            }
        endif;

        return redirect()->route('home')->with('success', 'Post atualizado e em análise.');
    }

    
    public function destroy($id)
    {
        $post = $this->post->find($id);
        $this->authorize('delete', $post);

        // dd($post->comment);
        try {
            $post->hasFile ? Storage::disk('public')->delete($post->hasFile->file->path) : '';
            if($post->comment->count() >= 1){

                foreach($post->comment as $item):
                    $item->delete();
                endforeach;
            }

            $post->delete();
            
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Erro ao exluir imagem. Por favor tente novamente.');
        }

        return redirect()->route('home')->with('success', 'Post apagado com sucesso.');
    }
}

app/Http/Controllers/user/UserController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use App\Models\File;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function index()
    {
        return view('user.index');
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        
    }

   
    public function show($id)
    {

    }

    
    public function edit($id)
    {
        $this->authorize('update', $this->user->find($id));
        return view('user.account.edit',['user' => $this->user->find($id)]);
    }

    
    public function update(Request $request, $id)
    {
        $user = $this->user->find($id);
        $this->authorize('update', $user);

        if($request->file):

            $validator = Validator::make($request->all(), [
                'file' => 'max:300',    
            ]);

            if ($validator->fails()) {
                return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
            }

            $file = new File;

            try {
                $file->upload($file, $request->file, auth()->user()->id);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error', 'Erro ao cadastrar imagem. Por favor tente novamente.');
            }
            $user->file_id = $file->id;
        endif;

        $user->setData($user, $request->all());
        

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Erro ao atualizar cadastro. Por favor tente novamente.');
        }



        return redirect()->route('home')->with('success', 'Dados atualizado com Sucesso!');
    }

    
    public function destroy(User $user)
    {
        //
    }
}

app/Http/Livewire/Posts/Lists.php
<?php

namespace App\Http\Livewire\Posts;

use Livewire\Component;
use App\Models\Post;
use Livewire\WithPagination;

class Lists extends Component
{
    use WithPagination;

    public $search;

    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        return view('livewire.posts.lists',[
            'posts' => Post::where('title', 'like', '%'.$this->search.'%')->orderBy('created_at', 'asc')->paginate(20)
        ]);
    }
}

resources/views/user/posts/create.blade.php
<x-site>
    <x-slot name="title">
        {{ __('Adiconar Novo Post') }}
    </x-slot>

    <x-slot name="content">
        <section class="container">
            <div class="pt-5 pb-4">
                <h3>
                    <strong>Nova Postagem</strong>
                </h3>
            </div>
            <div class="hr pt-4 pb-4">
                <p>Todos os campo com <em class="text-danger">*</em> são obrigatórios!</p>
                <hr>
            </div>
            <form class="posts-form" method="POST" enctype="multipart/form-data"
                action="{{ route('postagens.store') }}">
                @csrf
                @method('post')
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="">Título <em class="text-danger">*</em></label>
                        <input type="text" name="title" class="form-control @error('title') is-invalid @enderror"
                            value="{{ old('title') }}" placeholder="Título aqui">
                        @error('title')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="">Categoria <em class="text-danger">*</em></label>
                        <select name="category_id"
                            class=" rounded-0 form-control @error('category_id') is-invalid @enderror">
                            <option value="">Selecione Categoria</option>
                            @foreach ($categorys as $item)
                                <option value="{{ $item->id }}"
                                    {{ old('category_id') === $item->id ? 'selected' : '' }}>
                                    {{ $item->title }}
                                </option>
                            @endforeach
                        </select>
                        @error('category_id')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="file">Imagem <em class="text-danger">*</em></label>
                        <input type="file" name="file" class="form-control-file">
                        @error('file')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="link">YouTube (Post em video, colocar código do video do youtube) </label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">https://www.youtube.com/watch?v=</div>
                            </div>
                            <input type="text" name="link" class="form-control @error('link') is-invalid @enderror"
                                value="{{ old('link') }}">
                        </div>
                        @error('link')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for="content">Conteúdo <em class="text-danger">*</em></label>
                    <textarea name="content" id="content" cols="30" rows="10">{{ old('content') }}</textarea>
                    @error('content')
                        <small id="emailHelp" class="form-text text-danger">
                            {{ $message }}
                        </small>
                    @enderror
                </div>
                </div>
                <div class="text-right login">
                    <button type="submit" class="btn btn-success">Postar</button>
                </div>
            </form>
        </section>
        <x-slot name="js">
            <script src="https://cdn.ckeditor.com/4.16.0/basic/ckeditor.js"></script>
            <script>
                CKEDITOR.replace('content', {
                    height: 300
                });

            </script>
        </x-slot>
    </x-slot>
</x-site>

resources/views/user/posts/edit.blade.php
<x-site>
    <x-slot name="title">
        {{ __('Editar Post: ' . $post->title) }}
    </x-slot>

    <x-slot name="content">
        <section class="container">
            <div class="pt-5 pb-4">
                <h3>
                    <strong>Nova Postagem</strong>
                </h3>
            </div>
            <div class="hr pt-4 pb-4">
                <p>Todos os campo com <em class="text-danger">*</em> são obrigatórios!</p>
                <hr>
            </div>
            <form class="posts-form" method="POST" enctype="multipart/form-data"
                action="{{ route('postagens.update', ['postagen' => $post]) }}">
                @csrf
                @method('PUT')
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="">Título <em class="text-danger">*</em></label>
                        <input type="text" name="title" class="form-control @error('title') is-invalid @enderror"
                            value="{{ $post->title }}" placeholder="Título aqui">
                        @error('title')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="">Categoria <em class="text-danger">*</em></label>
                        <select name="category_id"
                            class=" rounded-0 form-control @error('category_id') is-invalid @enderror">
                            <option value="">Selecione Categoria</option>
                            @foreach ($categorys as $item)
                                <option value="{{ $item->id }}"
                                    {{ $post->category_id === $item->id ? 'selected' : '' }}>
                                    {{ $item->title }}
                                </option>
                            @endforeach
                        </select>
                        @error('category_id')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="file">Imagem (Subistituir imagem?)</label>
                        <input type="file" name="file" class="form-control-file">
                        @error('file')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="link">YouTube (Post em video, colocar código do video do youtube) </label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">https://www.youtube.com/watch?v=</div>
                            </div>
                            <input type="text" name="link" class="form-control @error('link') is-invalid @enderror"
                                value="{{ $post->link }}">
                        </div>
                        @error('link')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="content">Conteúdo <em class="text-danger">*</em></label>
                        <textarea name="content" id="content" cols="30" rows="10">{{ $post->content }}</textarea>
                        @error('content')
                            <small id="emailHelp" class="form-text text-danger">
                                {{ $message }}
                            </small>
                        @enderror
                    </div>
                </div>
                <div class="text-right login">
                    <button type="submit" class="btn btn-success">Postar</button>
                </div>
            </form>
        </section>
        <x-slot name="js">
            <script src="https://cdn.ckeditor.com/4.16.0/basic/ckeditor.js"></script>
            <script>
                CKEDITOR.replace('content', {
                    height: 300
                });

            </script>
        </x-slot>
    </x-slot>
</x-site>