routes/web.php
<?php
/*Services*/
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*Controller*/
use App\Http\Controllers\PagesController;
use App\Http\Controllers\HomeController;
/*Master*/
use App\Http\Controllers\m3\UsersController;
use App\Http\Controllers\m3\CategorysController;
use App\Http\Controllers\m3\CommentController;
use App\Http\Controllers\m3\PagesController as M3PagesController;
use App\Http\Controllers\m3\PostsController;
/*User*/
use App\Http\Controllers\user\UserController;
use App\Http\Controllers\user\PostController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PagesController::class, 'index'])->name('index');

Auth::routes(['verify' => true]);

Route::get('/home',[HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth','verified']], function () {
	
	//User
	Route::resource('conta', UserController::class);
	Route::resource('postagens', PostController::class);

	//Master
	Route::resource('categories', CategorysController::class);
	Route::resource('users', UsersController::class)->except([
		'create'
	]);
	Route::resource('posts', PostsController::class)->except([
		'create','store'
	]);
	Route::resource('comentarios', CommentController::class)->except([
		'index','create','edit',
	]);
	Route::resource('pages', M3PagesController::class)->except([
		'create','show','store','destroy'
	]);

	//Site
	Route::get('categoria/{slug}', [PagesController::class, 'posts'])->name('posts');
	Route::get('post/{slug}', [PagesController::class, 'post'])->name('post');
	Route::get('user/{slug}', [PagesController::class, 'user'])->name('user');
	Route::post('comments', [PagesController::class, 'comments'])->name('comments');
	Route::get('curti/{id}', [PagesController::class, 'curti'])->name('curti');
	
	
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\m3\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\m3\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade'); 
	Route::get('map', function () {return view('pages.maps');})->name('map');
	Route::get('icons', function () {return view('pages.icons');})->name('icons'); 
	Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\m3\ProfileController@password']);

	//Pages Statics
	Route::get('{slug}', [PagesController::class, 'pages'])->name('pages');	
});

app/Http/Controllers/api/UsersController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\User;

class UsersController extends Controller
{

    public function validated($request)
    {
        return Validator::make($request->all(), [
            'name' => ['required', 'min:3'],
            'email' => ['required', 'email:rfc,dns'],
            'cpf' => ['required'],
            'password' => ['required', 'confirmed', 'min:6']
        ]);

    }

    public function store(Request $request)
    {
        if (self::validated($request)->fails()) 
            return response()->json(['error' => self::validated($request)->errors()->first()]);

        $user = new User;
        $user->setData($user, $request->all());

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return response()->json(['error' => 'Erro ao realizar cadastro. Por favor tente novamente.']);
        }

        return response()->json(['success' => 'Usuário Cadastrado com Sucesso!']);
    }

    
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        //
    }

   
    public function update(Request $request, $id)
    {
        //
    }

  
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/m3/CategorysController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

use App\Http\Requests\CategoryRequest;

class CategorysController extends Controller
{
    
    public function index()
    {
        $this->authorize('viewAny', Category::class);
        return view('m3.categories.index');
    }
    
    public function create()
    {
        $this->authorize('create', Category::class);
        return view('m3.categories.create');
    }

    public function store(CategoryRequest $request)
    {
        $this->authorize('create', Category::class);

        $category = new Category($request->all());
        $category->user_id = auth()->user()->id;
        
        try {
            $category->save();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível salvar a categoria.');
        }
        
        return redirect()->route('categories.index')->with('success', 'Categoria inserida com sucesso!');
    }
 
    public function show(Category $category)
    {
        return view('m3.categories.show',[
            'category' => $category
        ]);
    }
   
    public function edit(Category $category)
    {
        return view('m3.categories.edit',['category' => $category]);
    }
  
    public function update(Request $request, Category $category)
    {
        $this->authorize('create', Category::class);
        
        try {
            $category->update($request->all());
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível salvar a categoria.');
        }
        
        return redirect()->route('categories.index')->with('success', 'Categoria atualizado com sucesso!');
    }
    
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);

        if(empty($category->post))
            return redirect()->back()->with('error', 'Exite Postagens com essa Categoria');

        try {
             $category->delete();
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'Não foi possível apagar a categoria.');
        }

        return redirect()->route('categories.index')->with('success', 'Categoria removido com sucesso!');
    }
}

app/Http/Controllers/m3/CommentController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Notifications\Comment\UpdateNotification;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Comment::class, 'comment');
    }

    public function index()
    {
        //
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        $comment = Comment::find($id);
        return view('m3.comments.show',['comment' => $comment]);
    }

    public function edit(Comment $comment)
    {
        //
    }

    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);
        $comment->content = $request->content;
        $comment->active = $request->active;

        try {
            $comment->save();
            $comment->notify(new UpdateNotification());
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao atualizar comentário');
        }

        return redirect()->route('posts.show',$comment->post)->with('success','Comentário atualizado com sucesso!');
    }

    public function destroy($id)
    {
        $comment = Comment::find($id);

        try {
            $comment->delete();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao apagar comentário');
        }

        return redirect()->route('posts.show',$comment->post)->with('success','Comentário apagado com sucesso!');
    }
}

app/Http/Controllers/m3/PagesController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Page;
use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Page::class, 'page');
    }
    
    public function index()
    {
        return view('m3.pages.index');
    }

    
    public function create()
    {
        return view('m3.pages.create');
    }

   
    public function store(Request $request)
    {
        try {
            Page::create($request->all());
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error','Erro ao cadastrar Página');
        }

        return redirect()->route('pages.index')->with('success','Página criada com sucesso.');
    }


    public function show(Page $page)
    {
        //
    }


    public function edit(Page $page)
    {
        return view('m3.pages.edit',['page' => $page]);
    }

    
    public function update(Request $request, Page $page)
    {
        try {
            $page->update($request->all());
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao atualizar Página');
        }

        return redirect()->route('pages.index')->with('success','Página atualizada com sucesso.');
    }


    public function destroy(Page $page)
    {
        //
    }
}

app/Http/Controllers/m3/PostsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\FeaturedPost;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class, 'post');
    }

    public function index()
    {
        return view('m3.posts.index');
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        //
    }

    
    public function show(Post $post)
    {
        return view('m3.comments.index',['post' => $post]);
    }

    
    public function edit(Post $post)
    {
        return view('m3.posts.edit', ['post' => $post, 'categorys' => Category::orderBy('title', 'asc')->get()]);
    }

    
    public function update(Request $request, Post $post)
    {
        try {
            $post->update($request->all());
            FeaturedPost::where('post_id',$post->id)->update(['active' => $request->featured_post, 'post_id' => $post->id]);
        } catch (\Throwable $th) {
            throw $th;
            return redirect()->back()->with('error', 'Erro ao atualizar post!');
        }

        return redirect()->route('posts.index')->with('success','Post atualizado com sucesso!');
    }

    
    public function destroy(Post $post)
    {
        try {
            $post->delete();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível apagar o post.');
        }

        return redirect()->back()->with('success', 'Post removido com sucesso!');
    }
}

app/Http/Controllers/m3/ProfileController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProfileRequest;
use App\Http\Requests\PasswordRequest;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    /**
     * Show the form for editing the profile.
     *
     * @return \Illuminate\View\View
     */
    public function edit()
    {
        return view('profile.edit');
    }

    /**
     * Update the profile
     *
     * @param  \App\Http\Requests\ProfileRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProfileRequest $request)
    {
        if (auth()->user()->id == 1) {
            return back()->withErrors(['not_allow_profile' => __('You are not allowed to change data for a default user.')]);
        }

        auth()->user()->update($request->all());

        return back()->withStatus(__('Profile successfully updated.'));
    }

    /**
     * Change the password
     *
     * @param  \App\Http\Requests\PasswordRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function password(PasswordRequest $request)
    {
        if (auth()->user()->id == 1) {
            return back()->withErrors(['not_allow_password' => __('You are not allowed to change the password for a default user.')]);
        }

        auth()->user()->update(['password' => Hash::make($request->get('password'))]);

        return back()->withPasswordStatus(__('Password successfully updated.'));
    }
}

app/Http/Controllers/m3/UsersController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, 'user');
    }
    
    public function index()
    {
        return view('m3.users.index');
    }

    
    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        $type = Role::where('name','User')->first();
        $user = new User;

        $user->setData($user, $request->all());   
        $user->role_id = $type->id;

        try {
            $user->save();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível cadastrar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário cadastrado com sucesso!');
    }

    
    public function show(User $user)
    {
        return view('m3.users.show',['user' => $user]);
    }

    
    public function edit(User $user)
    {
        return auth()->user()->role->name === "User" ? 
            redirect()->route('conta.edit', $user) : 
                view('m3.users.edit',['user' => $user]);
    }

    
    public function update(Request $request, User $user)
    {
        $user->setData($user, $request->all());

        try {
            $user->save();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error', 'Não foi possível atualizar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário atualizado com sucesso!');
    }

    
    public function destroy(User $user)
    {
        if(isset($user->post)):
            foreach($user->post as $item):
                $item->delete();
            endforeach;
        endif;

        try {
            $user->delete();
        } catch (\Throwable $th) {
            //throw $th;
            return redirect()->back()->with('error', 'Não foi possível apagar a usuário.');
        }

        return redirect()->route('users.index')->with('success', 'Usuário apagado com sucesso!');
    }
}

app/Http/Controllers/user/AdminController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view('user.index');
    }
}

app/Http/Livewire/Site/Posts/User.php
<?php

namespace App\Http\Livewire\Site\Posts;

use Livewire\Component;

class User extends Component
{
    public $user;
    public $date;
    public $post;

    public function render()
    {
        // dd($this->post->like->count());
        // dd($this->date->format('d-m-y'));
        return view('livewire.site.posts.user',['user' => $this->user,'date' => $this->date, 'post' => $this->post]);
    }
}

app/Http/Livewire/Users/Cards.php
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class Cards extends Component
{
    public $data;

    public function cards($item)
    {
        return [
            [
                'title' => 'Produtos',
                'icon' => 'shop text-default',
                'count' => $item->products->count(),
                'route' => 'companies.products.show',
                'id' => $item->id,
            ],
            [
                'title' => 'Slides',
                'icon' => 'tv-2 text-warning',
                'count' => $item->slides->count()
            ],
            [
                'title' => 'Configurações',
                'icon' => 'settings-gear-65 text-danger',
                'count' => $item->settings->count()
            ],
            [
                'title' => 'Logs',
                'icon' => "cloud-download-95 text-primary",
                'count' => $item->users->logs->count()
            ]
        ];
    }

    public function render()
    {
        return view('livewire.cards',['cards' => $this->cards($this->data)]);
    }
}

app/Http/Livewire/Users/Posts.php
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class Posts extends Component
{
    public $posts;

    public function render()
    {
        return view('livewire.users.posts',['posts' => $this->posts]);
    }
}

resources/views/m3/users/edit.blade.php
<x-layout.app>
    <x-slot name="title">
        {{ __('Usuários / ' . $user->name) }}
    </x-slot>

    <x-slot name="content">
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">Informações</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{{ route('users.update', $user) }}" autocomplete="off">
                                @csrf
                                @method('put')

                                <div class="form-group">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name"
                                        class="form-control form-control-alternative @error('name') is-invalid @enderror"
                                        placeholder="{{ __('Name') }}" value="{{ $user->name }}" required>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-name">{{ __('CPF') }}</label>
                                    <input type="text" name="cpf"
                                        class="form-control form-control-alternative @error('cpf') is-invalid @enderror"
                                        placeholder="{{ __('000.000.000-00') }}" value="{{ $user->cpf }}">

                                    @error('cpf')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email"
                                        class="form-control form-control-alternative @error('email') is-invalid @enderror"
                                        placeholder="{{ __('Email') }}" value="{{ $user->email }}" required>

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <div class="form-row">
                                        <div class="col-12 col-md-6">
                                            <label class="form-control-label"
                                                for="input-email">{{ __('Facebook') }}</label>
                                            <input type="url" name="facebook" id="input-email"
                                                class="form-control form-control-alternative @error('facebook') is-invalid @enderror"
                                                placeholder="{{ __('Facebook') }}" value="{{ $user->facebook }}">

                                            @error('facebook')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                        <div class="col-12 col-md-6">
                                            <label class="form-control-label"
                                                for="input-email">{{ __('Instagram') }}</label>
                                            <input type="url" name="instagram" id="input-email"
                                                class="form-control form-control-alternative @error('instagram') is-invalid @enderror"
                                                placeholder="{{ __('Instagram') }}"
                                                value="{{ $user->instagram }}">

                                            @error('instagram')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Atualizar') }}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">Senha</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{{ route('profile.password') }}" autocomplete="off">
                                @csrf
                                @method('put')
                                <div class="form-group">
                                    <label class="form-control-label"
                                        for="input-password">{{ __('Nova Senha') }}</label>
                                    <input type="password" name="password" id="input-password"
                                        class="form-control form-control-alternative @error('password') is-invalid @enderror"
                                        placeholder="{{ __('Nova Senha') }}" value="" required>

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label"
                                        for="input-password">{{ __('Confirme Senha') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password"
                                        class="form-control form-control-alternative @error('password_confirmation') is-invalid @enderror"
                                        placeholder="{{ __('Confirme Senha') }}" value="" required>

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="text-center">
                                    <button type="submit"
                                        class="btn btn-success mt-4">{{ __('Change password') }}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </x-slot>
</x-layout.app>

resources/views/m3/users/index.blade.php
<x-layout.app>
    <x-slot name="title">
        {{ __('Usuários') }}
    </x-slot>
    <x-slot name="content">
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        @livewire('users.lists')
                    </div>
                </div>
            </div>
        </div>
    </x-slot>
</x-layout.app>

resources/views/m3/users/show.blade.php
<x-layout.app>
    <x-slot name="title">
        {{ __('Usuários / ' . $user->name) }}
    </x-slot>

    <x-slot name="content">
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">Postagens</h3>
                                </div>
                                <div class="col-4 text-right">
                                    <input wire:model="search" class="form-control" type="text" placeholder="Pesquisar">
                                </div>
                                <div class="col-12">
                                    <div class="collapse pt-5{{ old('title') ? ' show' : '' }}" id="collapseExample">
                                        <form class="" method="post" action="{{ route('categories.store') }}">
                                            @csrf
                                            <div class="form-row">
                                                <div class="form-group col-12 col-md-12 col-lg-10 col-xl-11">
                                                    <input type="text" class="form-control" id="inlineFormInputName2"
                                                        name="title" placeholder="Categoria"
                                                        value="{{ old('title') }}">
                                                </div>
                                                <div class="form-group col-12 col-md-12 col-lg-2 col-xl-1">
                                                    <button type="submit"
                                                        class="btn btn-success mb-2 w-auto">Salvar</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @livewire('users.posts',['posts' => $user])
                    </div>
                </div>
            </div>
        </div>
    </x-slot>
</x-layout.app>